module.exports = [
    `This is the Global News Podcast from the BBC World Service.`,
    `Hello I'm Oliver Conway. And this edition is published in the early hours of Monday the 23rd of July. Our main stories:`,
    `A former Trump campaign adviser, Carter Page, has dismissed FBI allegations he collaborated with Russia, saying they are a complete joke. `,
    `An extreme right-winger in Brazil has confirmed that he will stand in presidential elections. `,
    `And the German footballer, Mesut Özil, is stepping down from the national team because of what he called racism and disrespect.`,
    `Also in this podcast:`,
    `The window surveillance pictures show three people are putting stones out of the backs and following them they spray can stop speciesism on the shop front. `,
    `In the past few weeks a fishmonger's and christian and a few days ago roast chicken place.`,
    `We'll hear about the militant vegetarians taking their fight to French food sellers.`,
    `Try as he might, President Trump appears unable to end speculation about the role played by Russia during the 2016 election campaign. `,
    `Now documents released by the FBI have revealed that investigators believed Mr Trump's foreign policy advisor – Carter Page – was conspiring and collaborating with Russian intelligence officers. Speaking on CNN, Mr Page categorically denied the accusations:`,
    `I've never been an agent of a foreign power by any stretch of the imagination. `,
    `You know, I may have, back in the G20 when they were getting ready to do that in St Petersburg, I might have participated in a few meetings that a lot of people, including people from the Obama administration, were sitting in on in Geneva, Paris etc but I've never been anywhere near what's being described here.`,
    `I asked our correspondent in Washington, Chris Buckler, to tell us about the FBI's suspicions.`,
    `If you take a look at these documents and there are four hundred pages of them all we should say a lot of them are redacted they're saying very clearly that they believe a quarter page was the subject of tog retired recruitment by the russian government.`,
    `They also say they believe that he had been collaborating and conspiring with the russian government and it also goes on to talk about potentially russia trying to undermine and influence the outcome of the twenty sixteen presidential election and of course all of this comes down to this question about quarter pitch himself.`,
    `His name might not be familiar to some but he was a foreign policy adviser during Donald Trump's campaign and his background is an energy industry consultant and sure enough he did a lot of conversations with russia.`,
    `He was a specialist in oil and gas in russia as well as parts of asia and specifically he's been asked about whether or not he does have a relationship with russia. `,
    `Nice dismiss this idea of ever been an agent of foreign powers he put that but he was asked several times: "do you have any relationships with russian government officials during an interview with CNN this morning and five or six times he feel to answer that directly.`,
    `I suspect the democrats will season that going forward has done denial. `,
    `There are these allegations still being investigated now they or potentially still being investigated and of course you've got to remember that these whole questions a boy whether or not there was interference in the election back in two thousand and sixteen or part of that special consul investigation involving Robert Mueller and we simply do not know exactly what Robert Mueller is looking at at any particular time.`,
    `So you could argue that its potential as far as door trumps concern though he is angry about all this he's been hitting night on twitter his favourite platform really attacking what he describes as as an attempt to spy on his campaign by the department of justice and the FBI also claims that they misled the court.`,
    `This is a suggestion because affected all this information or some of this information came from a dossier that was compiled by a man called Christopher Steel is a former British intelligence agent and it was funded by the democrat party but actually when you take a look at this they made that very clear and the judges were aware of that whenever they give this warrant.`,
    `Chris Buckler in Washington.`,
    `One of the most contentious figures in Brazilian politics, the extreme right wing politician Jair Bolsonaro has formally announced his candidature for the presidential elections in October. `,
    `He is currently second in the polls behind the former president, Luiz Inacio Lula da Silva - who is serving a prison sentence for corruption. Here's our Americas Editor, Candace Piette:`,
    `A former army officer, Jair Bolsonaro is followed by millions of Brazilians on social media. To his opponents he is a far-right agitator who insults women, and gay men and praises torturers from Brazil's military era. `,
    `To his supporters, he is Brazil's saviour.`,
    `Mr Bolsonaro says he wants to tackle growing crime by relaxing gun control laws. He also has the backing of millions of evangelical Christians for his uncompromising anti-abortion views. `,
    `But a large part of his popular appeal is that he is one of very few politicians untouched by Brazil's mammoth corruption investigations.`,
    `The Afghan vice president Abdul Rashid Dostum is a survivor of numerous conflicts from the Soviet occupation onwards. `,
    `Willing to change sides when it benefited him, he is a controversial figure, once accused of allowing hundreds of Taliban prisoners to be suffocated in shipping containers. `,
    `On Sunday, he returned to Afghanistan after more than a year in exile. `,
    `But as he left the airport, he narrowly escaped a suicide bomb attack. At least fourteen people died and around fifty were injured in the explosion. This man described what he saw:`,
    `"An ordinary person came, he looked normal like me, he was wearing black clothes. He talked to the police and I thought he was a suicide bomber, and suddenly an explosion happened, and I saw a number of people in pieces."`,
    `General Dostum was unhurt, and later addressed cheering supporters at his office. `,
    `James Coomarasamy spoke to Ahmed Rashid – a Pakistan-based author who has met General Dostum several times:`,
    `He is extremely thuggish either very violent man.`,
    `He's a very violent temper.`,
    `He's a heavy drinker, but he's also very charismatic and in the last thirty years of warfare.`,
    `He started out as a soldier put a communist army, served with the Soviets in Afghanistan in the Seventies and Eighties and then joined them what Eileen and later.`,
    `I'll be that many, many different roles, but his drinking has been really the cause of many problems because he tends to get extremely violent and react to anything that anyone says about him or to him when he's had a few drinks and of course, there's flies in the face of Islamic teachings and also what many of the Dalek barman.`,
    `Others hate about him.`,
    `Is that he had a very contemporary kind of man and a huge embarrassment.`,
    `Like many times to his old friend and allies like he has been to present gush of granny, which rather begs the question.`,
    `Why is he being invited back.`,
    `Well, you know he is the Vice President then ninety, had enlisted him in the last elections because he needed.`,
    `Use black vote, which was about ten million people right now viewed Becks are more divided have more anti feeling, but it's still a colossal Vote.`,
    `Bank and money needs it for the October elections, which will take place.`,
    `Hopefully, if all goes well.`,
    `The other thing is that I think there is talk about another ceasefire in August and at the moment.`,
    `There's chaos in northern of gonna start in Western have got their homeland of does them.`,
    `Many of his supporters out in the streets.`,
    `Criticising and attacking the government is also a very fierce battle going on between the government and the Dalek by.`,
    `I think this and somebody like those desperately needed by the government to try and re install law and order and get all the anti thought about forces on one side.`,
    `So I think that's another reason and the other reason is that there is talk of another ceasefire in the middle of August, when another religious festival take place.`,
    `Remember last month.`,
    `There was amazing three day ceasefire in which actually the Taleban and the government forces stop killing each other for just three days and there's a hope that.`,
    `Another ceasefire could prompt talks between the government and the ballet by dust and is needed for many, many reasons.`,
    `The journalist — Ahmed Rashid.`,
    `The founder of the Syrian rescue force known as the White Helmets has welcomed an operation by Israel to rescue more than a hundred of the group's volunteers. `,
    `They and their families were evacuated from southern Syria because of fears their lives were in danger. `,
    `Mark Lowen is monitoring developments from Turkey:`,
    `In the hell of Syria's war, the rescuers have had to be rescued. 422 people, members of the White Helmets and their families, were escorted by Israeli soldiers from the Syrian border into – and to safety. `,
    `They'll be resettled in Britain, Canada and Germany. As regime and Russian forces close in on an opposition area of southwest Syria, thousands have been given safe passage to the rebel-held north. But not the White Helmets, who President Assad calls "jihadists". `,
    `James Le Mesurier is a former British army officer who founded the White Helmets:`,
    `During previous evacuations earlier this year in Douma and in Homs, we saw the White Helmets volunteers that were trying to evacuate were quite literally hunted down by the regime and they were tortured, they were forced to make false confessions in front of a camera, and this extraordinary, morally depraved behaviour by the regime resulted in the initiation of this operation.`,
    `Nominated for the Nobel Peace Prize, the volunteers have been fearless, pulling victims from the rubble of airstrikes and performing first aid when hospitals have been bombed. `,
    `They say that they've saved over 115,000 lives. It was hoped more White Helmets could be evacuated - but they've been hemmed in by Islamic State fighters. `,
    `Resistance to Assad is crumbling. And a medical lifeline in southwest Syria has now been cut.`,
    `That report by Mark Lowen in Turkey.`,
    `So why did Israel intervene? `,
    `James Coomarasamy spoke to Joshua Landis — the head of the Centre for Middle East Studies at the University of Oklahoma:`,
    `They're doing a big favour for the United States and for the European powers in carrying out important humanitarian work we've noticed throughout the war.`,
    `Israel has taken in a number of Syrian rebels as well as their family members and civilians who've been wounded trees in their hospitals has tried to do humanitarian work in serious of course.`,
    `He's always been bombing serious the same time attacking you running emplacements Syrian placements shooting down the answer in plain, but for Israel.`,
    `This is about doing a good deed but as you allude to it's something that's happening on Israel's doorstep and he's very much share a military conflict that Israel is getting involved in as well.`,
    `Yes Israel has increasingly become involved in a serious civil war.`,
    `It has supported a number of rebel groups, hoping to build a small buffer zone that has collapsed now.`,
    `So, Israel has gone back to dealing with the outside Government, particularly through the Russians and this means that the rebels are collapsing and some of them are seeking asylum through Israel to the West.`,
    `How would you characterise the current state of the war in Syria.`,
    `The rebellion that started in two thousand eleven is now at an end the destruction of the dead are on clay in the south is de loused region were rebels fought against a government without foreign troops on the ground still almost forty percent of steering territory is still held by rebel groups that have supported by foreign militants in the north of Syria, the United States Special Forces hold about thirty percent of serious territory Turkish forces.`,
    `Allied with local rebel groups occupy another five to ten percent of Syrian territory in the north.`,
    `So the war art is far from over and thought about the the White Helmets, who remain.`,
    `It was thought that eight hundred or so people were were meant to be getting out, but so far, only four hundred twenty two are confirmed to have left the country under this operation.`,
    `What fate awaits those who were unable to leave the country think many of them will be persecuted by the Syrian government.`,
    `Very likely because they're seen as an arm of the rebellion.`,
    `Some of them may be able to escape persecution, but they are clearly going to be terrified.`,
    `Today, they have every reason to be extremely worried.`,
    `Just a final thought on this operation and the work that the Israelis have done it did used to be international organisations like the Red Cross who would do it.`,
    `Yes, it did, but it was much too dangerous to a parade in rebel territory in Syria the uniqueness of the White Helmets.`,
    `Is that they had good relations with most of the rebel malicious accepted their help and who knew them and trusted them so they could operate in the rebel held territories.`,
    `And this is what's so infuriated the Syrian government who accused them of being proxies in a sense of the rebel troops.`,
    `It was the uniqueness of the searing civil war were humanitarian organisations could not get in and and this underline.`,
    `Some of the ambiguities and difficulties of operating in Syria.`,
    `Joshua Landis from the University of Oklahoma.`,
    `Four years ago, he was celebrating winning the world cup with Germany. `,
    `But on Sunday, Mesut Ozil quit international football – accusing some in the German Football Association of racism. `,
    `The star – who is of Turkish origin – has faced criticism for having his photograph taken alongside Turkey's President Tayyip Erdogan. `,
    `In a social media post, he said "it is with a heavy heart that because of recent events, I will no longer be playing for Germany at international level whilst I have this feeling of racism and disrespect". `,
    `Archie Rhind Tutt is a sports journalist who specialises in German football:`,
    `As he is renowned for being one of the quieter members of the squad in terms we barely speak, speak to the media.`,
    `He explained his reasons for why he didn't do that in the aftermath, and he didn't feel that he was being listened to and the thing is that this is it opens up a much bigger bait than just football here.`,
    `It opens up the debate about dual nationality in Germany and indeed how that has been viewed and that is the biggest point is making here.`,
    `There's a still feels that he's been wronged in terms of there being double standards because before you had players like Miroslav Klose or for example of`,
    `Polish heritage as well with Lucas.`,
    `But do ski, but the point is that it was never brought up about them that they really had that or not to the same extent, anyway.`,
    `And that the treatment he has received has been completely different, which to be honest, given the way`,
    `that on their behalf.`,
    `The team manager of of the German FA and he did had Grindle, the German FA President have both moved towards scapegoating was ill since Germany got knocked out of the tournament.`,
    `You would have to say that as a point there. `,
    `The sports journalist, Archie Rhind Tutt.`,
    `He did make me realise that actually, there is gold dust to be found in the most unlikely of places he was the cause of the hole in the Wall restaurant but the rest was walk past.`,
    `The legacy of the American food critic, Jonathan Gold.`,
    `In recent years, China has faced a series of food and drug safety scares – now a scandal over faulty vaccines has forced the Chinese Premier to speak out. `,
    `Li Keqiang said the issue had crossed a "moral line" and he demanded punishment for those responsible. `,
    `Parents have been taking to social media to express their anger. `,
    `I heard more from our Asia Pacific editor, Michael Bristow:`,
    `What happened.`,
    `A few days ago. Is this particular company involved. Chang shown biotechnology and the name of the company means long life by the way.`,
    `It was revealed that he'd produced a rabies vaccine and in the process of that  they'd falsified some test records. If that wasn't bad enough.`,
    `A few days ago. We found out that there was a separate investigation into another batch of `,
    `vaccines for diphtheria, tetanus and whooping cough, which, again, were `,
    `substandard is suggested in that particular case that they've actually just didn't work, but.`,
    `Of course, if you're a parent who's had any of these factors. You would. Has my child had.`,
    `Yes So parents have been taking to social media to talk about this. How have the authorities responded.`,
    `First of all the parents. They've been very anxious saying things like I'm never gonna trust Chinese medicine again you can trust.`,
    `Even the things that you give to your children in future. I'm going to try and buy for whom medicine, instead of Chinese medicine.`,
    `Of course. Something like this.`,
    `The authorities are going to listen and they have a listen to it in China state run media usually very tightly control and they try to brush things under the carpet.`,
    `So this something like this happens. They say OK. We've got those responsible. Now, let's move on.`,
    `But interestingly, this has been all over the Chinese media.`,
    `The main television news has been reported that even editorials calling for a proper explanation.`,
    `And I think that's why. Finally, later on. On Sunday, a leak. A Chang.`,
    `The Chinese premier has come out and said, This has crossed a moral line and we really need to get to the bottom of it and find out who's responsible.`,
    `But at the same time there are reports that social media posts have been deleted by the other.`,
    `Indeed, because a lot of them are asking the obvious question is how on Earth time and time again is chine involved in these health scandals.`,
    `Ten years ago, if we remember there was a scandal over baby formula which was poisoned several children died many, many more were made ill because of that.`,
    `How is it that this company was allowed to make these vaccines found to be making them and find only a small amount of money.`,
    `We're talking about companies, earning billions and billions there on the change and stock exchanges.`,
    `Company would only find a small amount.`,
    `How is it that they were allowed to carry on producing potentially dangerous faxing.`,
    `So while the authorities want to acknowledge that parents have got an issue there.`,
    `Deleting their post because they don't want to let this.`,
    `Get out of hand, hoping that leak. Or Chang's comments can put a lid on it.`,
    `Michael Bristow.`,
    `The French President's former bodyguard, Alexandre Benalla, has been charged with "gang violence" after he was filmed beating May Day protesters. `,
    `Emmanuel Macron has been accused of being slow to respond to the actions of his close aide -- but finally intervened on Sunday evening. `,
    `Here's the BBC's Mathiew Leiser: `,
    `Alex and Anna are as well as an employee from prison across.`,
    `Polly were charged with gang violence.`,
    `Three other senior police officers have also been charged.`,
    `They've accused of helping been out to clear his name by giving him CCTV footage.`,
    `So the video shows Alexander and are dressed as a police officer beating a protester was meant to be only there to observe police operations and so the video shows extreme violence and his protester apparently prison macro knew about this on the same date happened, but only to spend.`,
    `He'd been out for two weeks. And now that Roman revealed this last week. The government decided to fire.`,
    `Nanna on Friday and cos you said as finally reacted No directly after meeting was high reveal ministers and a close associate just said that these acts from across an acceptable.`,
    `I will speak when he considers it is history.`,
    `And this case has not been and will not be treated with impunity.`,
    `Yes, it seems my crimes.`,
    `Finally, here taking some action about this how damaging is this for him and the government.`,
    `It's quite imagine for a moment because for example, the parliament in show us and said that to stop all debate still waiting on a major constitutional reform.`,
    `Stop this also opposition.`,
    `MP's Are Talking about Michael as he may have a secret police because they just found out that this guy.`,
    `Alexander been Anna had a badge to enter the National Assembly and it's also really bad for my call because he only a thirty nine percent of a priority right now regarding the last, Paul's and already thought there will be a big world cup.`,
    `Boom. You know, after to win from France. No, it didn't happen.`,
    `And in addition to that we just find out that my crawl gave Alex and a partial manor house on the scene reserved for his workers a car and a driver at the beginning of the month.`,
    `So this silence from the President creates more and more speculation about being as role in general `,
    `Mathiew Leiser.`,
    `Stop species-ism. That's the – difficult-to – slogan that's often sprayed in fake blood by militant vegetarians in a series of attacks on butcher's shops and restaurants across France. `,
    `Worried French butchers have even held a meeting with the country's Interior Minister to express their concern. `,
    `The largest number of attacks have been in the northern city of Lille -- from where John Laurenson reports:`,
    `One of the young butchers of the bush.`,
    `He dillisk, it was in the old part of lean prepares to cut that pride of culinary France, the rib steak onto cooked it was very care.`,
    `Cooked meats and store manager who discovered the damage. Have you had a kid who met my Paul gave her level.`,
    `She arrived early in the morning to open the shop and as soon as I turned the corner.`,
    `I saw it. The main shop window and a door, window with smashed and the side door had been damaged the window surveillance pictures.`,
    `Sure. Three people are putting stones out of the bags and throwing them off.`,
    `They spray can stop speciesism, on the shop front in the past few weeks.`,
    `A fishmongers, the Christian and and a few days ago.`,
    `Roast chicken place where also attacked Woods.`,
    `We were already attacked a year ago when they use fake blood and graffiti by and murder, sir.`,
    `But, um as I say a word of it customer Mattie silly stuff buys a pope's eye steak and some Polish sausage that the butcher is promoting at the moment.`,
    `She has no truck with vegan violence. It's stupid reason. Have you are to stop her evil.`,
    `We wanted to eat fish and meat to what is a problem, but they say it is because, er.`,
    `You're killing animals, you killing seventeen beings. You don't feel guilty about that.`,
    `No, out in the street. The BELLS TINKLE on for a surprisingly long time.`,
    `Every like quarter of an hour, reminding us that we're in the butter.Tomorrow. `,
    `That's broadly called the north, where towns have belfries and a local speciality is the fake.`,
    `And then along, deep fried hotdog made of minced chicken, pork and just that little bit of horse.`,
    `So all the people. I spoke to him leave except one American who just couldn't make her mind up condemned the attacks because they said we are free to eat what we want because our forebears were hunter gatherers and because people in general and the French in particular with them.`,
    `Frogs' Legs and snails and under yet. Pigs. Colon. Sausage and natural born. Omnivores.`,
    `As for France's new, but vocal animal rights lobbyists. Two. One for their spokesman co founder, Sebastian.`,
    `A sack also condemned the violence. More or less. But for bottom.`,
    `More. Yeah. In a secure. He says it's not necessarily a very intelligent way to move things forward.`,
    `It's a sign perhaps of frustration there was the food and farming bailed out just went through Parliament and it contained a number of animal rights amendment banning cages and the grinding up, have made chicks in exile, putting surveillance cameras in slaughterhouses, providing a vegetarian choice in school, but all of these amendments were voted down.`,
    `Bertie Ahern. Or you to son of you did have a because before I leave Li Lo, I meet the President of the northern French branch of the Independent butchers' Federation long ago.`,
    `He says that following the meeting with the Interior Minister.`,
    `He now expects the police to make arrests. What. Ask him.`,
    `If the violence continues. This is what was the perfect. We'd all agree.`,
    `We had decided not to lie low and wait for the storm to blow over my colleague said to me long.`,
    `This is the north. They want a fight. Let's give them a fight in this.`,
    `You heard this was all three years. A was he feels he go. Always built like a brick outhouse.`,
    `I think the expression is away in any case. That is probably.`,
    `Let's face it is more common among butchers among the Egan's the latter may be best advised for their health.`,
    `If not for their cause to keep your lawful from now on.`,
    `John Laurenson in Lille in northern France.`,
    `The UK's new Brexit minister has said he's confident an agreement can be reached by October on Britain's departure from the EU. `,
    `Dominic Raab says he'll return to Brussels for more talks this week. British business is divided over the benefits of leaving the EU. `,
    `One of the biggest backers is Tate and Lyle Sugars which has been importing sugar cane from Africa and the Caribbean for more than a century. `,
    `Here's an extract from a recent company advertisement:`,
    `So a "golden opportunity" says the company, which makes Golden Syrup. Gerard Mason is Tate and Lyle's Senior Vice President:`,
    `It is a golden opportunity for us at Tate and Lyle sugar is to go from job losses and downsizing to growth, investment in more good quality jobs and even more innovation.`,
    `So a golden opportunity. It says the company which makes golden syrup. Gerard Mason is ten miles.`,
    `Senior Vice President, this sugar is sugar crystals lets us by tariff free. But there's plenty of other sugar.`,
    `They charge the tariffs on their vessels that coming. Where we pay tariffs.`,
    `They can be three or four million euros each. We have to send to Brussels and in a normal year.`,
    `We probably spend about thirty to forty million euros on tariff costs or cost been inflated by these restrictions that Europe.`,
    `Place summers. We need. Britain to have an independent trade policy.`,
    `We also need that independent trade policy to be workable for businesses like ours.`,
    `In theory. The white paper allows the UK to have an independent trade policy in practice.`,
    `The mechanism that will be used to join the police.`,
    `The UK's In the used tariffs is what we're confused about if that's designed in a way that works for businesses like ours.`,
    `We really can take advantage of trade deals that UK.`,
    `STRIKES That's great if it's not. Then it's true.`,
    `We have a trade policy in principle, but not in practice. John Mason of Tate and Lyle.`,
    `Jonathan Gold, the first restaurant critic to win the Pulitzer Prize for Criticism, has died at the age of fifty-seven. `,
    `Exploring eateries in every corner of Los Angeles he introduced readers to dozens of cuisines and even helped the city understand itself. `,
    `The British food critic, Jay Rayner, was in touch with him over the years:`,
    `The brilliant thing about Jonathan Gould was that he took a very complicated city.`,
    `Los Angeles and made it seem small. I had been going for it to LA.`,
    `For about twenty years and tie. Finely clock.`,
    `What gold had been saying which was that.`,
    `It was not a city about its fancy restaurants to really understand the city.`,
    `You had to get into the ethnic patchwork that was.`,
    `I mean, he always denied the term out. Polish.`,
    `He said it was a restaurant critic, but there was something about the way he wrote in whichhe communicated the diversity of a city.`,
    `He wrote as a fan. It's interesting that he was a music writer on before you was food writer and he wrote withthat enthusiasm, but I found it was also a really good understanding.`,
    `Hell cultures, work and telling me that if you wanted to go to a really classical careerrestaurant.`,
    `You're more likely to find it in Los Angeles than you would in Seoul, Korea because in LosAngeles.`,
    `It's an act of remembrance was insulting career.`,
    `That's a career looking to the future where is in looking to the past.`,
    `That was Jay Rayner on Jonathon Gold who's died at the age of fifty seven.`,
    `In a TV first, the next series of the American programme, Supergirl, will feature a transexual superhero. `,
    `The young actress Nicole Maines, who's trans herself, will play the part of Dreamer. `,
    `There's been controversy over non-trans actors being cast in the roles.  `,
    `Charlotte Gallagher has this report: `,
    `Activists have hailed the casting of Nicole mains is near. Now, who becomes known as a superhero. Dreamer.`,
    `It's a first for television and main says it's only fitting that there's going to be a trans superhero for trans kids to look up to, but she says her story lines won't solely focus on her gender identity.`,
    `Adding she hopes viewers will realise trans people can do anything they want to and Supergirl actress is used to fighting battles in twenty fourteen when she was just seventeen.`,
    `She went to court when her school stopped using the girls' Toilet.`,
    `Recently, the issue of non trans actors being cast in Trans roles has been causing controversy.`,
    `Scarlett Johansson dropped out of a film.`,
    `Following intense criticism while the Magic Mike star Matt boma was attacked on line for playing a trans woman in the movie, anything.`,
    `The CW Network, which produces Supergirl has also announced he's developing a television adaptation of Batwoman, whether superhero will be a lesbian.`,
    `Ironically, the character was first introduced by DC Comics in the nineteen fifties as a love interest for Batman to dispel rumours he was gay.`,
    `Charlotte Gallagher.`,
    `And that's all from us for now - but there will be an updated version of the Global News podcast later.`,
    `If you want to comment on this podcast - or the topics covered in it - you can send us an email - the address is globalpodcast@bbc.co.uk. `,
    `I'm Oliver Conway. Until next time, goodbye.`
]
